# -*- coding: utf-8 -*-
"""MLProjectCatBoost.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YTQaqoBuOmrgpIuw2gCCzNdZcbAApFX_
"""

import pandas as pd 
import numpy as np
from catboost import CatBoostClassifier, Pool, cv
import os
from sklearn.model_selection import train_test_split

train = pd.read_csv("C:/Users/User/Desktop/Kyu/train_sample_shuffle.csv")

train = train.iloc[:,1:]

train.shape

train.columns = ["id","click","hour","C1","banner_pos","site_id","site_domain","site_category","app_id","app_domain","app_category","device_id","device_ip","device_model",
"device_type","device_conn_type","C14","C15","C16","C17","C18","C19","C20","C21"]

train_count=int(len(train) * 0.9)

X_train = train.iloc[:train_count,2:]
y_train = train.iloc[:train_count, 1]

X_train.shape

X_val = train.iloc[train_count:,2:]
y_val = train.iloc[train_count:,1]

X_val.shape

cat_features = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

model = CatBoostClassifier(
    random_seed = 42,
    custom_loss=['Logloss'],
    bagging_temperature = 1,
    iterations=350,
    learning_rate = 0.3,
    task_type = "GPU",
    boosting_type = "Ordered",
    depth = 6,
    l2_leaf_reg = 5,
    random_strength = 1,
    od_type = "Iter",
    od_wait = 50
)

model.fit(
    X_train, y_train,
    cat_features=cat_features,
    eval_set=(X_val, y_val),
    verbose = 10
    )

model2 = CatBoostClassifier(
    random_seed = 42,
    custom_loss=['Logloss'],
    bagging_temperature = 1,
    iterations=350,
    learning_rate = 0.5,
    task_type = "GPU",
    boosting_type = "Ordered",
    depth = 6,
    l2_leaf_reg = 5,
    random_strength = 1,
    od_type = "Iter",
    od_wait = 50
)

model2.fit(
    X_train, y_train,
    cat_features=cat_features,
    eval_set=(X_val, y_val),
    verbose = 10
    )

model3 = CatBoostClassifier(
    random_seed = 42,
    custom_loss=['Logloss'],
    bagging_temperature = 1,
    iterations=350,
    learning_rate = 0.3,
    task_type = "GPU",
    boosting_type = "Plain",
    depth = 6,
    l2_leaf_reg = 5,
    random_strength = 1,
    od_type = "Iter",
    od_wait = 50
)

model3.fit(
    X_train, y_train,
    cat_features=cat_features,
    eval_set=(X_val, y_val),
    verbose = 10
    )

test = pd.read_csv("C:/Users/User/Desktop/Kyu/ProjectTestData.csv")

test = test.iloc[:,1:]

test_probs = model3.predict_proba(test)

sample_sub = pd.read_csv(r"C:\Users\User\Desktop\Kyu\ProjectSubmission-Team2.csv")

sample_sub["click"] = test_probs[:,1]

sample_sub.to_csv("ProjectSubmission-Team2.csv", index = False)